version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
        user: root
    working_directory: ~/ncs
    environment:
      BASH_ENV: /root/.bashrc
    steps:
      - checkout

      - run:
          name: Set up GitHub credentials
          command: echo "machine github.com login ${GH_USERNAME} password ${GH_TOKEN}" > ~/.netrc

      # Download and cache dependencies
      - restore_cache:
          keys:
            - deps-{{ checksum "west.yml" }}
            # fallback to using the latest cache if no exact match is found
            - deps-

      - run:
          name: Install Zephyr dependencies
          command: |
            apt-get -y install ninja-build gperf python3-pip
            pip3 install --user cmake
            pip3 install --user west
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV

      - restore_cache:
          keys:
            - gcc-arm-none-eabi-7-2018-q2-update
      - run:
          name: GCC ARM Embed
          command: |
            if [ ! -d ~/ncs/gcc-arm-none-eabi-7-2018-q2-update ]; then
                wget 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update' -O ~/ncs/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2;
                tar xjf ~/ncs/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2;
            fi
            echo 'export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb' >> $BASH_ENV
            echo 'export GNUARMEMB_TOOLCHAIN_PATH="~/ncs/gcc-arm-none-eabi-7-2018-q2-update"' >> $BASH_ENV
      - save_cache:
          paths:
            - ~/ncs/gcc-arm-none-eabi-7-2018-q2-update
          key: gcc-arm-none-eabi-7-2018-q2-update

      - restore_cache:
          keys:
            - device-tree-compiler_1.4.7-1_amd64.deb
      - run:
          name: Device Tree Compile 1.4.7
          command: |
            wget -nc 'http://mirrors.kernel.org/ubuntu/pool/main/d/device-tree-compiler/device-tree-compiler_1.4.7-1_amd64.deb' -O ~/device-tree-compiler_1.4.7-1_amd64.deb || true
            dpkg -i ~/device-tree-compiler_1.4.7-1_amd64.deb
      - save_cache:
          paths:
            - ~/device-tree-compiler_1.4.7-1_amd64.deb
          key: device-tree-compiler_1.4.7-1_amd64.deb

      - run:
          name: West init
          command: |
            west init -m https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME --mr $CIRCLE_SHA1
            west update
            pip3 install --user -r zephyr/scripts/requirements.txt
            pip3 install --user -r nrf/scripts/requirements.txt
            pip3 install --user -r mcuboot/scripts/requirements.txt

      - save_cache:
          paths:
            - ~/ncs/zephyr
            - ~/ncs/modules
            - ~/ncs/mcuboot
            - ~/ncs/nrfxlib
            - ~/ncs/test
            - ~/ncs/mbedtls
            - ~/.cache/pip
            - ~/.local/lib/python3.7/site-packages
            - ~/.local/bin
          key: deps-{{ checksum "west.yml" }}

      - run:
          name: Build
          command: |
            cd ~/ncs/nrf/applications/cat_tracker
            west build -b nrf9160_pca20035ns
            sha256sum ~/ncs/nrf/applications/cat_tracker/build/zephyr/merged.hex

      - run:
          when: on_success
          name: Run semantic relase
          command: |
            npm i --no-save semantic-release;
            npx semantic-release || true

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: bifravst
