name: Build and Release

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BROKER_HOSTNAME: ${{ secrets.BROKER_HOSTNAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Preserve PIP cache
        id: cache-pip
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip.cache/pip
          key: ${{ runner.OS }}-pip

      - name: Cache GCC ARM Embed binary
        id: cache-gcc-arm
        uses: actions/cache@v1
        with:
          path: gcc-arm/
          key: ${{ runner.OS }}-gcc-arm-none-eabi-7-2018-q2-update-linux

      - name: Download GCC ARM Embed
        if: steps.cache-gcc-arm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/gcc-arm/
          wget 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2018q2/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2?revision=bc2c96c0-14b5-4bb4-9f18-bceb4050fee7?product=GNU%20Arm%20Embedded%20Toolchain,64-bit,,Linux,7-2018-q2-update' -O ${GITHUB_WORKSPACE}/gcc-arm/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2

      - name: Install GCC ARM Embed
        run: |
          tar xjf ${GITHUB_WORKSPACE}/gcc-arm/gcc-arm-none-eabi-7-2018-q2-update-linux.tar.bz2

      - name: Cache Device Tree Compile binary
        uses: actions/cache@v1
        id: cache-dtc
        with:
          path: device-tree-compiler/
          key: ${{ runner.OS }}-device-tree-compiler_1.4.7-1_amd64.deb

      - name: Download Device Tree Compile 1.4.7
        if: steps.cache-dtc.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/device-tree-compiler/
          wget 'http://mirrors.kernel.org/ubuntu/pool/main/d/device-tree-compiler/device-tree-compiler_1.4.7-1_amd64.deb' -O ${GITHUB_WORKSPACE}/device-tree-compiler/device-tree-compiler_1.4.7-1_amd64.deb

      - name: Install Device Tree Compile 1.4.7
        run: |
          sudo dpkg -i ${GITHUB_WORKSPACE}/device-tree-compiler/device-tree-compiler_1.4.7-1_amd64.deb

      # Workaround for https://github.com/NordicSemiconductor/pc-nrfutil/issues/288
      - name: Install latest PIP
        run: |
          sudo python3 -m pip install -U pip
          # Newer PIP will not overwrite distutils, so upgrade PyYAML manually
          sudo apt-get install python3-setuptools
          sudo python3 -m pip install --ignore-installed -U PyYAML

      - name: Install Zephyr dependencies
        run: |
          sudo apt-get -y install ninja-build gperf python3-pip python3-setuptools
          sudo pip3 install cmake west wheel

      - name: West init
        run: |
          export PATH=~/.local/bin:$PATH
          west init -m https://github.com/${GITHUB_REPOSITORY} --mr ${GITHUB_SHA}
          west update
          sudo pip3 install -r zephyr/scripts/requirements.txt
          sudo pip3 install pc_ble_driver_py
          sudo pip3 install -r nrf/scripts/requirements.txt
          sudo apt-get -y remove python-cryptography python3-cryptography
          sudo pip3 install -r mcuboot/scripts/requirements.txt

      - name: Patch West to enable nrf9160_pca10015ns
        run: |
          patch -b ${GITHUB_WORKSPACE}/zephyr/cmake/app/boilerplate.cmake < ${GITHUB_WORKSPACE}/nrf/.github/workflows/zephyr.patch

      - name: Determine next release version
        run: |
          npm ci
          export NEXT_VERSION=`node ${GITHUB_WORKSPACE}/nrf/.github/workflows/get-next-version.js`
          echo -n $NEXT_VERSION > .version
          echo "CONFIG_CAT_TRACKER_APP_VERSION=\"$NEXT_VERSION\"" >> ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/prj.conf

      - name: Configure the AWS IoT broker hostname
        run: echo "CONFIG_AWS_IOT_BROKER_HOST_NAME=\"${BROKER_HOSTNAME}\"" >> ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/prj.conf

      - name: Build
        run: |
          export ZEPHYR_TOOLCHAIN_VARIANT=gnuarmemb
          export GNUARMEMB_TOOLCHAIN_PATH=${GITHUB_WORKSPACE}/gcc-arm-none-eabi-7-2018-q2-update
          export PATH=~/.local/bin:$PATH
          cd ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker
          mkdir -p -v ${GITHUB_WORKSPACE}/.cache
          export XDG_CACHE_HOME=${GITHUB_WORKSPACE}/.cache
          # NB-IoT
          west build -p auto -b nrf9160_pca20035ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-app_update.bin
          west build -p auto -b nrf9160_pca10090ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-app_update.bin
          west build -p auto -b nrf9160_pca10015ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-app_update.bin
          # LTE-m
          sed -i s/CONFIG_LTE_NETWORK_MODE_NBIOT_GPS=y/CONFIG_LTE_NETWORK_MODE_NBIOT_GPS=n/ ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/prj.conf
          sed -i s/CONFIG_LTE_LEGACY_PCO_MODE=y/CONFIG_LTE_LEGACY_PCO_MODE=n/ ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/prj.conf
          west build -p auto -b nrf9160_pca20035ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-ltem.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-ltem-app_update.bin
          west build -p auto -b nrf9160_pca10090ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-ltem.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-ltem-app_update.bin
          west build -p auto -b nrf9160_pca10015ns
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/merged.hex ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-ltem.hex
          mv ${GITHUB_WORKSPACE}/nrf/applications/cat_tracker/build/zephyr/app_update.bin ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-ltem-app_update.bin

      - name: Release
        if: startsWith(github.ref, 'refs/heads/saga')
        run: |
          wget https://github.com/github/hub/releases/download/v2.12.8/hub-linux-amd64-2.12.8.tgz
          tar xzf hub-linux-amd64-2.12.8.tgz
          export NEXT_VERSION=`cat .version`
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns.hex cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-app_update.bin cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION-app_update.bin
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns.hex cat-tracker-PCA20035-Thingy52-$NEXT_VERSION.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-app_update.bin cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-app_update.bin
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns.hex cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-app_update.bin cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-app_update.bin
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-ltem.hex cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION-ltem.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10015ns-ltem-app_update.bin cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION-ltem-app_update.bin
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-ltem.hex cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-ltem.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca20035ns-ltem-app_update.bin cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-ltem-app_update.bin
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-ltem.hex cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-ltem.hex
          cp -v ${GITHUB_WORKSPACE}/nrf/cat-tracker-nrf9160_pca10090ns-ltem-app_update.bin cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-ltem-app_update.bin
          ./hub-linux-amd64-2.12.8/bin/hub release create -m "$NEXT_VERSION" -a "cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION.hex#Pre-build HEX file for PCA10015 / Asset Tracker ($NEXT_VERSION) NB-IoT" -a "cat-tracker-PCA20035-Thingy52-$NEXT_VERSION.hex#Pre-build HEX file for PCA20035 / Thingy:91 ($NEXT_VERSION) NB-IoT" -a "cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION.hex#Pre-build HEX file for PCA10090 / nRF9160 DK ($NEXT_VERSION) NB-IoT" -a "cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION-ltem.hex#Pre-build HEX file for PCA10015 / Asset Tracker ($NEXT_VERSION) LTE-m" -a "cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-ltem.hex#Pre-build HEX file for PCA20035 / Thingy:91 ($NEXT_VERSION) LTE-m" -a "cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-ltem.hex#Pre-build HEX file for PCA10090 / nRF9160 DK ($NEXT_VERSION) LTE-m" -a "cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-app_update.bin#Pre-build App Update file for PCA20035 / Thingy:91 ($NEXT_VERSION) NB-IoT" -a "cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-app_update.bin#Pre-build App Update file for PCA10090 / nRF9160 DK ($NEXT_VERSION) NB-IoT" -a "cat-tracker-PCA10015-AssetTracker-$NEXT_VERSION-ltem-app_update.bin#Pre-build App Update file for PCA10015 / Asset Tracker ($NEXT_VERSION) LTE-m" -a "cat-tracker-PCA20035-Thingy52-$NEXT_VERSION-ltem-app_update.bin#Pre-build App Update file for PCA20035 / Thingy:91 ($NEXT_VERSION) LTE-m" -a "cat-tracker-PCA10090-nRF9160DK-$NEXT_VERSION-ltem-app_update.bin#Pre-build App Update file for PCA10090 / nRF9160 DK ($NEXT_VERSION) LTE-m" $NEXT_VERSION
